<<<<<<< HEAD
# Site settings
title: Daniella Roberts
email: roberts.1611@osu.edu
description: > # this means to ignore newlines until "baseurl:"
  My awesome website (In construction)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  daniellaro

# Build settings
markdown: kramdown
=======
theme: jekyll-theme-cayman
>>>>>>> 9ddf446d4ecb0537473a8820786fbbef8ce1d755
